# Конфигурационный файл для программы RPCYummyAnime

# Адрес мастер-сервера, с которым будет взаимодействовать приложение.
# Не меняйте это значение, если не уверены в необходимости изменений.
api_url: "rpc.yani.tv"

# Статус активности по умолчанию.
# Значение true означает, что активность будет установлена при запуске,
# значение false — активность будет выключена по умолчанию.
default_is_active: false

# Цветовой режим иконки.
# Если true, иконка будет цветной, если false — черно-белой.
colorized_icon: true